python3: can't open file 'collect_vul_info.py': [Errno 2] No such file or directory
